<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:template match="/">
    <html>
      <head>
        <title><xsl:value-of select="rss/channel/title"/> - Feed</title>
        <style type="text/css">
          body {
            font-family: 'Segoe UI', Tahoma, sans-serif;
            background: transparent;
            color: #eee;
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            line-height: 1.6;
          }
          .header {
            border-bottom: 2px solid orange;
            margin-bottom: 30px;
            padding-bottom: 10px;
          }
          h1 { color: orange; margin: 0; }
          .subtitle { color: #888; font-size: 0.9em; }
          .item {
            background: #2a2a2a;
            padding: 20px;
            margin-bottom: 20px;
            border-radius: 8px;
            border-left: 4px solid orange;
          }
          .item-title {
            font-size: 1.2em;
            font-weight: bold;
            margin-bottom: 5px;
          }
          .item-title a {
            color: #fff;
            text-decoration: none;
          }
          .item-title a:hover { text-decoration: underline; }
          .item-date {
            font-size: 0.8em;
            color: #aaa;
            margin-bottom: 10px;
          }
          .footer {
            text-align: center;
            margin-top: 50px;
            font-size: 0.8em;
            color: #666;
          }
          #metro-icons-container {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: -1;
            pointer-events: none;
            overflow: hidden;
          }
          .metro-icon {
            position: absolute;
            pointer-events: none;
            user-select: none;
            opacity: 0.15;
            transition: opacity 0.5s ease;
            filter: brightness(0) invert(1);
          }
        </style>
      </head>
      <body>
        <div id="metro-icons-container"></div>
        <div class="header">
          <h1><xsl:value-of select="rss/channel/title"/></h1>
          <p class="subtitle"><xsl:value-of select="rss/channel/description"/></p>
        </div>
        
        <xsl:for-each select="rss/channel/item">
          <div class="item">
            <div class="item-title">
              <a href="{link}"><xsl:value-of select="title"/></a>
            </div>
            <div class="item-date"><xsl:value-of select="pubDate"/></div>
            <div class="item-description">
              <xsl:value-of select="description" disable-output-escaping="yes"/>
            </div>
          </div>
        </xsl:for-each>

        <div class="footer">
          Generated by ZC2 RSS Pipeline --thorns
        </div>
        <script src="assets/js/rss-bg.js"></script>
        <script src="assets/js/metro-bg.js"></script>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
