<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:template match="/">
    <html>
      <head>
        <title><xsl:value-of select="rss/channel/title"/> - Feed</title>
        <style type="text/css">
          @font-face {
            font-family: 'Kronika';
            src: url('../fonts/KRONIKA.ttf') format('truetype');
          }
          body {
            font-family: 'Segoe UI', Tahoma, sans-serif;
            background: transparent;
            color: #eee;
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            line-height: 1.6;
          }
          .header {
            border-bottom: 2px solid orange;
            margin-bottom: 40px;
            padding-bottom: 10px;
          }
          @keyframes wobble {
            0%, 100% { transform: rotate(-5deg) translateY(0); }
            50% { transform: rotate(5deg) translateY(-5px); }
          }
          h1 { 
            color: orange; 
            margin: 0; 
            display: inline-block;
            font-family: 'Kronika', sans-serif;
          }
          h1 span {
            display: inline-block;
            animation: wobble 2s ease-in-out infinite;
            transform-origin: center;
            white-space: pre;
          }
          .subtitle { color: #888; font-size: 0.9em; }
          .item {
            background: #4c4c4c;
            background: linear-gradient(to bottom,  #4c4c4c 0%,#595959 12%,#666666 25%,#474747 39%,#2c2c2c 50%,#000000 51%,#111111 60%,#2b2b2b 76%,#1c1c1c 91%,#131313 100%);
            margin-bottom: 30px;
            border-radius: 12px;
            border: 1px solid #555;
            overflow: hidden;
            box-shadow: 0 8px 24px rgba(0,0,0,0.6);
          }
          .item-title {
            background: #fffe6e;
            background: linear-gradient(to bottom,  #fffe6e 0%,#ffea51 22%,#ffd842 33%,#ffc133 44%,#fbad22 51%,#fbad22 51%,#ee8800 52%,#e07b00 63%,#ce6a00 74%,#b85500 85%,#9e3d00 96%,#923200 100%);
            padding: 12px 20px;
            font-size: 1.3em;
            font-weight: bold;
            color: #000;
            text-shadow: 0 1px 0 rgba(255,255,255,0.4);
            border-bottom: 1px solid #923200;
            font-family: 'Kronika', sans-serif;
          }
          .item-title a {
            color: #000;
            text-decoration: none;
          }
          .item-title a:hover { text-decoration: underline; }
          .item-content-wrap {
            padding: 20px;
            color: #eee;
          }
          .item-date {
            font-size: 0.8em;
            color: #aaa;
            margin-bottom: 10px;
          }
          .footer {
            text-align: center;
            margin-top: 50px;
            font-size: 0.8em;
            color: #666;
          }
          #metro-icons-container {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: -1;
            pointer-events: none;
            overflow: hidden;
          }
          .metro-icon {
            position: absolute;
            pointer-events: none;
            user-select: none;
            opacity: 0.15;
            transition: opacity 0.5s ease;
            filter: brightness(0) invert(1);
          }
        </style>
      </head>
      <body>
        <div id="metro-icons-container"></div>
        <div class="header">
          <h1>
            <xsl:call-template name="wobble-text">
              <xsl:with-param name="text" select="rss/channel/title"/>
            </xsl:call-template>
          </h1>
          <p class="subtitle"><xsl:value-of select="rss/channel/description"/></p>
        </div>
        
        <xsl:for-each select="rss/channel/item">
          <div class="item">
            <div class="item-title">
              <xsl:value-of select="title"/>
            </div>
            <div class="item-content-wrap">
              <div class="item-date"><xsl:value-of select="pubDate"/></div>
              <div class="item-description">
                <xsl:value-of select="description" />
              </div>
            </div>
          </div>
        </xsl:for-each>

        <div class="footer">
          Generated by ZC2 RSS Pipeline --thorns
        </div>
        <script>
          // <![CDATA[
          // hybrid hydration for browsers that block disable-output-escaping (Firefox/Safari) --thorns
          window.addEventListener('DOMContentLoaded', () => {
            document.querySelectorAll('.item-description').forEach(el => {
              // if browser didn't render tags (literal <p> etc. visible)
              if (el.innerHTML.indexOf('&lt;') !== -1 || el.innerHTML.indexOf('<') !== -1) {
                el.innerHTML = el.textContent;
              }
            });
          });
          // ]]>
        </script>
        <script src="assets/js/rss-bg.js"></script>
        <script src="assets/js/metro-bg.js"></script>
      </body>
    </html>
  </xsl:template>

  <xsl:template name="wobble-text">
    <xsl:param name="text"/>
    <xsl:param name="index" select="0"/>
    <xsl:if test="string-length($text) > 0">
      <span style="animation-delay: {$index * 0.1}s;">
        <xsl:value-of select="substring($text, 1, 1)"/>
      </span>
      <xsl:call-template name="wobble-text">
        <xsl:with-param name="text" select="substring($text, 2)"/>
        <xsl:with-param name="index" select="$index + 1"/>
      </xsl:call-template>
    </xsl:if>
  </xsl:template>
</xsl:stylesheet>
